[package]
name = "server"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
env_logger = "0.9.0"
app = {path="../app"}
serde = "1.0.137"
serde_json = "1.0.81"
thiserror = "1.0.31"
